### ISSUE TITLE
Update the engine versions

### ISSUE THREAD

**Issue by anastasialanz** [sparkbox/sparkle#72]
We currently have Sparkle in a client and when installing the latest version `1.4.3`, it says that the engines are unsupported. Sparkle is still working correctly even with this warning. Can we specify more versions of node and npm?

![image](https://user-images.githubusercontent.com/3081483/119670060-93948f00-be06-11eb-8feb-935a8a237a03.png)

https://github.com/sparkbox/sparkle/blob/77dc92e0bb0dca8dd18562cb0b7993eb206384f4/package.json#L28-L30

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

**Comment by robtarr** [comment]
Can we change that to 
```
"node": ">=12.0.0", 
"npm": ">=6.0.0"
```
